version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_db: laravel_scratch
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '4606:3306'
  apache:
    container_name: apache
    build:
      context: ./php
    ports:
      - '8081:80'
    volumes:
      - ./src:/var/www/laravel_scratch
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
